# Generated by Django 4.0.2 on 2022-03-18 15:04

from django.db import migrations
from file_extractor.constants import NER_ENTITIES_TAGS

def seed_tags(apps, schema_editor):
    NEREntityTag = apps.get_model('file_extractor', 'NEREntityTag')
    tagList = []

    for key, value in NER_ENTITIES_TAGS.items():
        item = NEREntityTag(id=value, name=key, description='')
        tagList.append(item)

    NEREntityTag.objects.bulk_create(tagList)



class Migration(migrations.Migration):


    dependencies = [
        ('file_extractor', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_tags),
    ]
